### PR TITLE
Fix AmqpMessagingSpanExtractor issue when message contains B3 headers

### PR DESCRIPTION
**Pull request by picaron**
Fix for issue https://github.com/netshoes/spring-cloud-sleuth-amqp/issues/21

### CODE REVIEW

**Comment by stwa** [comment]
Looks good for me. We would also like to have this fix merged :)

**Comment by picaron** [comment]
@ignacio83 can you please have a look ?

**Comment by picaron** [comment]
@stwa I see you are contributor on the project, are you able to merge the PR ?

seems there hasnt been activity on this repo since 2018

**Comment by picaron** [comment]
I give up

**Comment by BuJo** [comment]
Yeah, we just forked it internally mid last year and rebuilt our environment on that.. Thank you for your work @picaron

**Pull request closed without merging**
